### PR TITLE
Add docker image

### PR DESCRIPTION
**Pull request by MyTheValentinus**
Hello,
I just add docker image, at beginning created for mac (but not work due do --device limitation on docker for mac engine). But it bay me usefull for people with specific environnement on linux or do not whant to install the tool globaly on their system.
Thanks

### CODE REVIEW

**Comment by MyTheValentinus** [comment]
Hey @gjmvervoort 
Can you accept or refuse this PR ? I'm waiting to add new feature on this utility. (HTML Datatable export)
Thanks

**Comment by fdev** [comment]
Thanks for your suggestion to add docker.

> But it bay me usefull for people with specific environnement on linux  or do not whant to install the tool globaly on their system.

There's no need to install the tool globally, you can just run `python setup.py --user` to install the tool and its dependencies for the current user. There's not even a need to install the tool at all, you can run it using `python -m bc125csv` from the repository root (after installing the dependencies using `pip install pyudev pyserial`).

Adding docker seems a bit unnecessary, as environments that can run the docker cli should have no problem running this tool.

The only tricky bit about this tool is having read/write access to the device. On some systems this will require `sudo` or a permission change. This will not change or become easier when using docker.

> I'm waiting to add new feature on this utility. (HTML Datatable export)

A HTML table export feature is outside the scope of this tool. There are plenty of ways (eg. https://gist.github.com/jschaub30/c67cf9e214d83accd4db) to convert the CSV output to a HTML table; that does not need to be incorporated in this tool.

**Comment by vdeville** [comment]
Ok no problem, i will make a fork to add the function. When you have lot of channel in multi bank il much easier to have databale html web page to search into. Thanks

**Comment by fdev** [comment]
> Ok no problem, i will make a fork to add the function.

Excellent!

> When you have lot of channel in multi bank il much easier to have databale html web page to search into.

My scanner has most banks and channels filled up as well. I have an Excel file (with formatting, comments and sections that I can copy/paste from as needed) that I maintain and export to CSV when I want to push it to the device.

The exported CSV file is read by Excel (or LibreOffice Calc) just fine as well, and can be searched using Excel's search feature.

**Pull request closed without merging**
